import {
  ArrayMinSize,
  IsArray,
  IsDateString,
  IsEnum,
  IsInt,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  Min,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";

const ShipmentPriority = { LOW: "LOW", MEDIUM: "MEDIUM", HIGH: "HIGH", URGENT: "URGENT" } as const;

const ShipmentAssignmentMode = { AUTO: "AUTO", MANUAL: "MANUAL", UNASSIGNED: "UNASSIGNED" } as const;

export type ShipmentAssignmentMode = (typeof ShipmentAssignmentMode)[keyof typeof ShipmentAssignmentMode];

export class CreateStockRequestLineDto {
  @IsUUID() productId: string;
  @IsInt() @Min(1) requiredQuantity: number;
}

export class CreateStockRequestDto {
  @IsString() @MaxLength(40) requestType: string;
  /** Optional external customer/order reference. The internal REQ number is generated by the backend. */
  @IsOptional() @IsString() @MaxLength(80) referenceNumber?: string;
  @IsString() @MaxLength(120) requestedFor: string;
  @IsDateString() requiredDate: string;
  @IsOptional() @IsString() @MaxLength(500) notes?: string;
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => CreateStockRequestLineDto)
  lines: CreateStockRequestLineDto[];
}

export class ReleaseReservationDto {
  @IsString() @MaxLength(300) reason: string;
}

export class ReservationReasonDto {
  @IsString() @MaxLength(300) reason: string;
}

export class PrepareShipmentDto {
  @IsUUID() allocationId: string;
  @IsInt() @Min(1) quantity: number;
  @IsEnum(ShipmentAssignmentMode) assignmentMode: "AUTO" | "MANUAL" | "UNASSIGNED";
  @IsOptional() @IsUUID() assignedToId?: string;
  @IsOptional() @IsDateString() dueAt?: string;
  @IsOptional() @IsEnum(ShipmentPriority) priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
  @IsOptional() @IsString() @MaxLength(500) instructions?: string;
  /** Optional external courier / delivery-note / tracking reference. The system-generated SHIP reference is never replaced. */
  @IsOptional() @IsString() @MaxLength(80) externalReference?: string;
}
