ALTER TYPE "StockRequestStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_FULFILLED';
ALTER TYPE "StockRequestStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
ALTER TYPE "StockReservationStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
